name: xeus-kernel
channels:
  - https://prefix.dev/emscripten-forge-dev
  - https://prefix.dev/conda-forge
dependencies:
  # Kernele
  - xeus-python
  - xeus-r
  - xeus-sqlite

  # Python – podstawowy stack data science
  - pip
  - ipycanvas
  - ipywidgets
  - ipyleaflet
  - jinja2
  - matplotlib
  - numpy
  - pandas
  - scipy
  - plotly
  - networkx
  - pydot
  - simpy
  - sympy

  # R – baza + CourseKata
  - r-base
  - r-coursekata
  # (opcjonalnie, jawne zapewnienie core tidyverse)
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-readr
  - r-tibble
  - r-stringr
  - r-forcats
  - r-lubridate
