name: xeus-kernel
channels:
  - https://prefix.dev/emscripten-forge-dev
  - https://prefix.dev/conda-forge
dependencies:
  - xeus-python
  - xeus-r
  - xeus-sqlite
  - ipycanvas
  - ipywidgets
  - ipyleaflet
  - jinja2
  - matplotlib
  - numpy
  - pandas
  - scipy
  - plotly
  - networkx
  - simpy
  - sympy
  - r-base
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-readr
  - r-tibble
  - r-stringr
  - r-forcats
  - r-lubridate
  - r-broom
  - r-jsonlite
  - r-rmarkdown
